### ISSUE TITLE
EduOne bugs

### ISSUE THREAD

**Issue by kcmongalo** [profkaygee/EduOne#6]
Logout button is not available, can we have it
Add solutions to a problem to responding, like I cannot submit solutions 
Solution counter says 4 Solutions while I can only see one solution on the problem
So tutors when they register, they send an email to us and we do it for them(the registration) then email them their login details. Can u register me as a tutor?

**Comment by profkaygee** [comment]
Logout button is not available, can we have it - This has always been there, but you had to swpie to the right to expose the menu. I added a menu button so we can use it to expose the menu instead.

**Comment by profkaygee** [comment]
Add solutions to a problem to responding, like I cannot submit solutions - This was a regular expressions issue, this has been fixed.

**Comment by profkaygee** [comment]
Solution counter says 4 Solutions while I can only see one solution on the problem - This has been fixed. there was an issue with the solution count update

**Comment by profkaygee** [comment]
So tutors when they register, they send an email to us and we do it for them(the registration) then email them their login details. Can u register me as a tutor? - I will send you an email explaining this
